bug/VOGRE-13
diging/vogon-resuscitate pull request #10
Opened 2024-10-15 15:29 UTC by Girik1105

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 

Importing texts: text list seems to only show the first 50 texts

Description:
not all of them

https://diging.atlassian.net/browse/VOGRE-13?atlOrigin=eyJpIjoiYWIyZjNhN2JkZWZmNGM1NTkzZjQ3MjhiNTBlMzdmY2IiLCJwIjoiaiJ9

## Are there any other pull requests that this one depends on?
No
  
## Anything else the reviewer needs to know?

... describe here ...

2024-10-29 19:44 UTC, jdamerow requested changes

2024-10-29 19:44 UTC, jdamerow commented on repository/managers.py
> +                break
alright, we need to change that. there needs to be a citesphere endpoint to get the information about a specific collection. let me see if I merge now or wait till that is there.

2024-10-29 19:44 UTC, jdamerow commented on repository/managers.py
> +        total_pages = (collection_num_items // 50) + (1 if collection_num_items % 50 else 0)
50 needs to be a value from settings. it might change.

2024-10-29 19:44 UTC, jdamerow commented on repository/managers.py
> +        for page in range(2, total_pages + 1):
only one page at a time should be retrieved from citesphere, not all.

2024-10-31 18:48 UTC, jdamerow requested changes

2024-10-31 18:48 UTC, jdamerow commented on repository/managers.py
> +        base_url = f"{self.repository.endpoint}/api/v1/groups/{groupId}/collections/{collectionId}/items/"
that's not the base url but the url to get the items from, isn't it?

2024-10-31 18:48 UTC, jdamerow commented on repository/managers.py
> +        total_items = next((c.get('numberOfItems', 0) for c in collections_data if c.get('key') == collectionId), 0)
let's add a todo here that this needs to be changed once there is a collection info endpoint

2024-10-31 20:03 UTC, jdamerow commented
not sure what's going wrong, but I don't see any texts, just collections when I go to a group (texts do show up in a collection)

2024-10-31 20:06 UTC, Girik1105 commented
> not sure what's going wrong, but I don't see any texts, just collections when I go to a group (texts do show up in a collection)

The texts in a group is another ticket [VOGRE-10](https://diging.atlassian.net/browse/VOGRE-10?atlOrigin=eyJpIjoiZmVjYmM1MjQ1NjQxNGJmNWI1YWIxMmViZDRhYmJhMzciLCJwIjoiaiJ9)

2024-10-31 20:08 UTC, jdamerow commented
ah,ok.

2024-10-31 20:09 UTC, merged