Story/VOGRE-8
diging/vogon-resuscitate pull request #12
Opened 2024-10-22 23:32 UTC by rajvi-patel-22

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
 
https://diging.atlassian.net/browse/VOGRE-8

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2024-10-23 21:23 UTC, jdamerow commented
Please make sure to provide the ticket title if there is no description.

2024-10-23 21:30 UTC, jdamerow requested changes

2024-10-23 21:30 UTC, jdamerow commented on annotations/views/rest_views.py
> +                    concept['authority'] = {'name': 'Unknown'}
the contents of this loop looks like it could be more DRY by extracting a method and reuse it here and in `search`?

2024-11-07 20:45 UTC, jdamerow requested changes

2024-11-07 20:45 UTC, jdamerow commented on annotations/views/rest_views.py
> +    if concept['uri'].startswith(('http://www.digitalhps.org/', 'https://www.digitalhps.org/')):
those should be a setting in case this changes

2024-11-14 20:30 UTC, jophals commented on annotations/views/rest_views.py
> +            'pos': pos if pos else '',
So if `''` is passed for `pos` then this will result in a 400 error from ConceptPower. Passing `None` will actually return 'Any' pos

2024-11-19 15:26 UTC, merged