story/VOGRE-12
diging/vogon-resuscitate pull request #14
Opened 2024-10-31 15:11 UTC by Girik1105

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
This ticket requires to show the user all files associated with a specific text in citesphere and allow the user to import any inidivudal file the user would like.

# Multiple texts for a Citesphere entry

Description:
Citesphere entries can have more than one text attached to them (right now I think the first one will be used?).
The text table should list all the file names that are attached to a record, and then instead of an “Import”  button, there should be an import icon next to each file.

https://diging.atlassian.net/browse/VOGRE-12?atlOrigin=eyJpIjoiNWJjMWNmMGJiYWYyNDdmMzkyYmIyZWMyMGZiMTA0MTEiLCJwIjoiaiJ9

## Are there any other pull requests that this one depends on?
No
  
## Anything else the reviewer needs to know?

I Updated the `repository_text_import` view to support file-specific imports by using `file_id` as part of the unique identifier (`uri`). This change ensures that each file import, even for the same `text_key`, creates or updates a distinct `Text` object. The view now returns `JsonResponse`, providing error messages and a `redirect_url` for successful imports, since now all files are being rendered via AJAX.

2024-10-31 21:35 UTC, Girik1105 commented
Once bug/VOGRE-10 is merged into develop, I'll update this PR to incorporate the individual file import for group texts as well, currently only the collection texts are being done.

2024-11-21 17:33 UTC, jdamerow requested changes

2024-11-21 17:33 UTC, jdamerow commented on annotations/views/repository_views.py
> +    except Exception as e:
this exception should be logged as a minimum (it should probably shown to the user as well).

2024-11-21 17:33 UTC, jdamerow commented on annotations/views/repository_views.py
> +        return JsonResponse({'error': 'An error occurred while accessing the repository.'}, status=500)
error needs to be logged

2024-11-21 17:33 UTC, jdamerow commented on repository/managers.py
> +            if giles_uploads:
if a file is still being process, there will only be a progress id, not an extracted text. Vogon should probalby indicate a file is still being processed.

2024-12-12 20:44 UTC, jdamerow commented
Resolve conflicts please

2024-12-19 19:04 UTC, jdamerow commented
Resolve conflicts please

2025-01-17 18:33 UTC, jdamerow requested changes

2025-01-17 18:33 UTC, jdamerow commented on annotations/templates/annotations/project_list.html
> +        $.ajax({
Does this really have to be an ajax call? it seems like the view could redirect whereever it needs to go (that would also solve the issue I have below).

2025-01-17 18:33 UTC, jdamerow commented on annotations/templates/annotations/project_list.html
> +                alert('Failed to import text. Redirecting to projects page...');
javascript alerts are really ugly. if the view redirects appropriately after text import, then the error message can be shown on the next screen easily.

2025-01-17 18:33 UTC, jdamerow commented on annotations/views/repository_views.py
> +        return JsonResponse(item_data)
merge with previous line

2025-01-21 15:15 UTC, jdamerow requested changes

2025-01-21 15:15 UTC, jdamerow commented on annotations/templates/annotations/repository_collection.html
> +    console.log(window.config.APP_ROOT);
remove

2025-01-21 15:15 UTC, jdamerow commented on annotations/views/repository_views.py
> +        return render(request, 'annotations/repository_ioerror.html', {'error': 'An error occurred while accessing the repository.'}, status=500)
this template has Erick's email address in it. No email address is fine.

2025-01-21 15:15 UTC, jdamerow commented
Make it so, Jenkins.

2025-01-21 15:22 UTC, jdamerow commented
after that should be good

2025-01-24 15:02 UTC, jdamerow commented
Make it so, Jenkins.

2025-01-24 15:34 UTC, merged