story/VOGRE-7
diging/vogon-resuscitate pull request #15
Opened 2024-11-05 15:10 UTC by Girik1105

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
Get rid of celery and submit quaduples on request
Description

Currently, quadruples are submitted via Celery on a cron job. Celery should be completely removed. Instead a project should have a button that will submit quadrupes to Quadriga. This ticket includes multiple tasks:
Quadruples need to have a flag (if they don’t already) that indicates if they ahve been submitted or not
Quaduples need to be submitted to the new Quadriga 2.0
Only quadruples with complete relationships (in which concepts have been resolved and added to conceptpower) should be submitted.

(https://diging.atlassian.net/browse/VOGRE-7?atlOrigin=eyJpIjoiNjRlZWM4ZDUwM2Y1NGIzYmEwNWJiOGM3NDZlNDMyZjgiLCJwIjoiaiJ9)[VOGRE-7]

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2024-11-08 15:00 UTC, jdamerow requested changes

2024-11-08 15:00 UTC, jdamerow commented on .env_app-example
> +QUADRIGA_COLLECTION_ID=
this is something that needs to be set for each project. Every project can have a different collection it submits quadruples to.

2024-11-08 15:00 UTC, jdamerow commented on annotations/middleware.py
> +    check_interval = timedelta(minutes=5)  # Adjust the interval as needed
needs to be configurable through settings

2024-11-08 15:00 UTC, jdamerow commented on annotations/models.py
> +        ('not_ready', 'Not Ready'),
the first value here should be defined in constants, so the constants can be used elsewhere (see below)

2024-11-08 15:00 UTC, jdamerow commented on annotations/models.py
> +            self.status = 'not_ready'
in line 920 and 922 the constants defined above should be sued

2024-11-08 15:00 UTC, jdamerow commented on annotations/utils.py
> +            "creationTime": timezone.now().strftime('%Y-%m-%d'),
this should be the time an appellation was created

2024-11-08 15:00 UTC, jdamerow commented on annotations/utils.py
> +            "creationPlace": "phoenix",
let's leave that empty for now

2024-11-08 15:00 UTC, jdamerow commented on annotations/utils.py
> +            "sourceUri": concept.authority if hasattr(concept, 'authority') else ""
this needs to be the the uri of the text that has been annotated, so for now let's use the the url of the annotated text

2024-11-08 15:00 UTC, jdamerow commented on annotations/utils.py
> +            "sourceUri": concept.authority if hasattr(concept, 'authority') else ""
the above comments apply to all contexts

2024-11-08 15:00 UTC, jdamerow commented on annotations/utils.py
> +def generate_graph_data(relationset, user):
is this the same function as above?

2024-11-08 15:00 UTC, jdamerow commented on annotations/views/rest_views.py
> +        if relationset.status != 'ready_to_submit':
use constant here

2024-11-08 15:00 UTC, jdamerow commented
Also, there are conflicts

2024-11-28 02:03 UTC, jdamerow requested changes

2024-11-28 02:03 UTC, jdamerow commented on annotations/middleware.py
I don't think this is the right approach. It is likely to cause memory issues once there are sufficiently many relationsets. It also seems unnecessary. The only time we care about the readiness of a relation to be submitted is when we want to submit them or maybe when we look at a text. So it really only needs to be checked when the page shows all relations, and then only the relations that are relevant (not all of them).

2024-11-28 02:03 UTC, jdamerow commented on annotations/utils.py
> +
these two functions are specific to the quadriga api, aren't they? They should not be in the annotations util file.

2024-11-28 02:03 UTC, jdamerow commented on annotations/views/rest_views.py
> +        if relationset.status != 'ready_to_submit':
this still

2024-11-28 02:03 UTC, jdamerow commented on annotations/views/rest_views.py
> +        if relationset.status != 'ready_to_submit':
and everywhere else where these strings are used

2024-11-28 02:03 UTC, jdamerow commented on concepts/tasks.py
> +    pass
remove commented out code

2024-11-28 02:03 UTC, jdamerow commented on vogon/__init__.py
> +# Django starts so that shared_task will use this app.
are these comments still valid?

2024-11-28 02:03 UTC, jdamerow commented
Resolve conflicts please

2024-12-06 23:19 UTC, Girik1105 commented on annotations/middleware.py
> I don't think this is the right approach. It is likely to cause memory issues once there are sufficiently many relationsets. It also seems unnecessary. The only time we care about the readiness of a relation to be submitted is when we want to submit them or maybe when we look at a text. So it really only needs to be checked when the page shows all relations, and then only the relations that are relevant (not all of them).

If we only show the relations that can be submitted, then the user will not be able to see all relations that they have created on the text. Can we still show the relations that cannot be submitted with the disabled checkbox? I'll change the way we check for ready relations.

2024-12-12 20:44 UTC, jdamerow commented
Resolve conflicts please

2025-01-17 18:44 UTC, jdamerow requested changes

2025-01-17 18:44 UTC, jdamerow commented on .env_app-example
> +export QUADRIGA_ENDPOINT=
this needs to have an example (as a comment), e.g http://quadriga.instance/quadriga/...whatever else needs to be here/

2025-01-17 18:44 UTC, jdamerow commented on annotations/annotators.py
> +from annotations.models import TextCollection, Text
is this needed here?

2025-01-17 18:44 UTC, jdamerow commented on annotations/quadriga.py
> +            "termParts": [
there should be one term part for every piece of annotated text in an appellation (I think currently there can only be one term part as vogon doesn't allow highlighting multiple parts that are not together for one appellation). Position needs to be the position of the first character of the term part.

2025-01-17 18:44 UTC, jdamerow commented on annotations/quadriga.py
> +                    "expression": concept.label or "",
expresssion is the annotated text

2025-01-17 18:44 UTC, jdamerow commented on annotations/quadriga.py
> +            nodes[obj_id] = build_concept_node(obj, user, creation_time, source_uri)
what about nested relations, in which subject or object are a relation?

2025-01-17 18:44 UTC, jdamerow commented on annotations/views/rest_views.py
> +            response.raise_for_status()
all the quadriga related things should happen in a quadriga file or class

2025-01-17 18:44 UTC, jdamerow commented on vogon/__init__.py
> +# Django starts so that shared_task will use this app.
?

2025-02-04 15:58 UTC, jdamerow requested changes

2025-02-04 15:58 UTC, jdamerow commented on annotations/models.py
> +    STATUS_SUBMITTED = 'submitted'
let's keep those with the chioce field they are used in

2025-02-04 15:58 UTC, jdamerow commented on annotations/quadriga.py
> +        })
I'm confused, I don't think this is correct. per appellation there might be more than one term part, but those term parts are not coming from more than one appellation. 
appellation -has -> concept
appellation -has -> term parts

but not all term parts for all appellations should be collapsed into one node. Does that make sense?

2025-02-04 15:58 UTC, jdamerow commented on annotations/quadriga.py
> +            "termParts": term_parts
per appellation event, there should only be the term parts belonging to that appellation (not all appellations with the same concept).

2025-02-04 15:58 UTC, jdamerow commented on annotations/quadriga.py
> +            nodes[obj_id] = build_concept_node(obj, user, creation_time, source_uri)
this still I think

2025-02-04 15:58 UTC, jdamerow commented on annotations/views/rest_views.py
> +            print("ERROR", e)
needs to use logger

2025-02-28 01:56 UTC, jdamerow requested changes

2025-02-28 01:56 UTC, jdamerow commented on annotations/models.py
> +        else:
doesn't this set `status` and `submitted` even if those have already the correct values? That seems unnecessary.

2025-02-28 01:56 UTC, jdamerow commented on annotations/quadriga.py
> +    pos = appellation.startPos if appellation.startPos is not None else 0
hm, no, 0 and None is different. if there is no start position then there is probably no word actually being annotated. in that case we probably want to keep pos None (or null or whatever the json value is), as 0 would indicate the annotated word starts at position 0.

2025-02-28 01:56 UTC, jdamerow commented on annotations/quadriga.py
> +    if hasattr(appellation.interpretation, 'master') and hasattr(appellation.interpretation.master, 'uri'):
what is "master"?

2025-02-28 01:56 UTC, jdamerow commented on annotations/quadriga.py
> +            "creationPlace": "phoenix",
The value of this one should be configurable.

2025-02-28 01:56 UTC, jdamerow commented on annotations/quadriga.py
> +            "sourceUri": concept_source_url
this should be the uri of the text

2025-02-28 01:56 UTC, jdamerow commented on annotations/quadriga.py
> +    }
not sure I understand what this is doing, but the default relation would need to be configured in the template that what used to create a relation.

2025-03-12 22:50 UTC, Girik1105 commented on annotations/quadriga.py
> +    if hasattr(appellation.interpretation, 'master') and hasattr(appellation.interpretation.master, 'uri'):
This is used to get the highest-level merge target, its a concept [Model function](https://github.com/diging/vogon-resuscitate/blob/story/VOGRE-7/concepts/models.py#L94). This would help us get the concept's uri if available or else it will fallback to the text's uri which is the vogon uri (Example: urn:repository:1:item:ZVIGSRR8:file:FILEs8vb4PIqOQB7)

2025-03-12 23:13 UTC, Girik1105 commented on annotations/quadriga.py
> +            "sourceUri": concept_source_url
This is the concept node that is why I added the concept's uri instead of the text uri, I add the text uri in the graph data ([implementation](https://github.com/diging/vogon-resuscitate/blob/story/VOGRE-7/annotations/quadriga.py#L418)). Should I replace this also as the text uri instead?

2025-03-20 17:43 UTC, jdamerow requested changes

2025-03-20 17:43 UTC, jdamerow commented on annotations/models.py
> +                if self.submitted:
how could that be set to true? if the status is not submitted, then this should be false, right?

2025-03-20 17:43 UTC, jdamerow commented on annotations/models.py
> +                    changed = True
```suggestion
               self.status = self.STATUS_READY_TO_SUBMIT if self.status != self.STATUS_READY_TO_SUBMIT
               self.submitted = False
               self.save()
```

2025-03-20 17:43 UTC, jdamerow commented on annotations/models.py
> +            if self.status != self.STATUS_NOT_READY:
is this check necessary? if the object is not ready, then it should be ignored, right?

2025-03-20 17:43 UTC, jdamerow commented on annotations/quadriga.py
> +    if hasattr(appellation.interpretation, 'master') and hasattr(appellation.interpretation.master, 'uri'):
But that's not a text uri, it's a concept?

2025-03-20 17:43 UTC, jdamerow commented on annotations/quadriga.py
> +            "sourceUri": concept_source_url
yes, source uri should always be the uri of the annotated text

2025-03-20 17:43 UTC, jdamerow commented on annotations/quadriga.py
> +    default_mapping = {}
the default mapping should be coming from the template used to create a relation

2025-03-20 17:43 UTC, jdamerow commented on annotations/views/rest_views.py
> +        pk = request.data.get('pk')
bad variable name. pk of what?

2025-04-04 14:35 UTC, jdamerow requested changes

2025-04-04 14:35 UTC, jdamerow commented on annotations/forms.py
> +            'placeholder': 'How does the concept behave? (e.g. teaches, influences)'
what is this for? what's the concept behavior?

2025-04-04 14:35 UTC, jdamerow commented on annotations/forms.py
> +                raise forms.ValidationError("All fields are required when using relation nodes input")
I don't understand what this message means

2025-04-04 14:35 UTC, jdamerow commented on annotations/models.py
> +        else:
this still

2025-04-04 14:35 UTC, jdamerow commented on annotations/quadriga.py
> +    if hasattr(appellation.interpretation, 'master') and hasattr(appellation.interpretation.master, 'uri'):
?

2025-04-04 14:35 UTC, jdamerow commented on annotations/quadriga.py
> +    if template_part.source_node_type == 'CO':  # Specific concept
For all these strings, the appropriate constant from models should be used.

2025-04-04 14:35 UTC, jdamerow commented on annotations/quadriga.py
> +        }
all three parts of the default mapping could be either a specific concept or a reference to a node in the graph.

2025-04-04 14:35 UTC, closed without merging

2025-04-04 22:53 UTC, Girik1105 commented on annotations/forms.py
> +            'placeholder': 'How does the concept behave? (e.g. teaches, influences)'
This is the predicate, I'll change the placeholder

2025-04-04 23:11 UTC, Girik1105 commented
https://github.com/diging/vogon-resuscitate/pull/15#discussion_r2028907535

Ive set the function so works by first checking if the RelationSet is ready for submission using the ready() method, which checks is the concepts are resolved and ready to be submitted. If the RelationSet is ready and hasn't been submitted yet, the method updates its status to STATUS_READY_TO_SUBMIT and ensures the submitted flag is set to False, indicating it's prepared but not yet submitted. The else part verifies if the RelationSet isn't ready, it sets the status to STATUS_NOT_READY and also marks it as not submitted.