story/VOGRE-23
diging/vogon-resuscitate pull request #28
Opened 2024-12-03 18:04 UTC by Girik1105

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
There should be a user type: Vogon Admin

Description
Vogon admins should have access to the templates (and can edit/add/delete them), but not the Django admin site.

[VOGRE-23](https://diging.atlassian.net/browse/VOGRE-23?atlOrigin=eyJpIjoiNmM2M2ZhMTc3MmZiNDc1MGFjOTQ0ZjdmZTg0ZGU3NTEiLCJwIjoiaiJ9)

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

I have added a panel called Vogon Admin Panel (can be access through the dropdown) which is only available to super users where they can browse through users in the application and toggle Vogon Admin status.

[VOGRE-23]: https://diging.atlassian.net/browse/VOGRE-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-19 23:43 UTC, jophals commented on annotations/exceptions.py
> +    return render(request, 'annotations/forbidden_error_page.html', context, status=403)
did something here change?

2024-12-19 23:55 UTC, jophals commented on annotations/templates/annotations/header.html
> +                            {% if user.is_staff or user.is_vogon_admin %}<li><a href="{% url "list_relationtemplate" %}">Templates</a></li>{% endif %}
probably best to be consistent with your quoting syntax. Various {% %} blocks utilize double quotes inside and outside whereas some utilize double quotes outside and single quotes inside (I think single quotes inside is generally the popular choice)

2024-12-19 23:58 UTC, jophals commented on annotations/templates/annotations/header.html
> -        </div><!--/.container-fluid -->
what happened to this div (container-fluid)? Is it not needed? Because the opening div tag is still there but it's never closed

2024-12-20 00:14 UTC, jophals commented on annotations/decorators.py
> +def vogon_admin_required(view_func):
is there a situation where a Django admin (staff) would be denied access but a Vogon admin granted access? Based on the Admin User management access toggling, it seems that Django admin trumps Vogon admin...

2025-01-16 17:01 UTC, Girik1105 commented on annotations/exceptions.py
> +    return render(request, 'annotations/forbidden_error_page.html', context, status=403)
Nothing changed here, I thought its a blank space but that didn't fix the issue when I added one.

2025-01-21 15:35 UTC, jdamerow requested changes

2025-01-21 15:35 UTC, jdamerow commented on annotations/exceptions.py
> +    return render(request, 'annotations/forbidden_error_page.html', context, status=403)
It's probalby spaces vs tabs is my guess.

2025-01-21 15:35 UTC, jdamerow commented on annotations/views/user_views.py
> +@staff_member_required
I think this should be admin. I don't think we really use the staff role at this point, do we?

2025-01-21 15:35 UTC, jdamerow commented on annotations/views/user_views.py
> +@staff_member_required
same here

2025-01-24 15:42 UTC, jdamerow commented
Make it so, Jenkins.

2025-01-24 15:55 UTC, merged