Story/VOGRE-32
diging/vogon-resuscitate pull request #33
Opened 2024-12-16 22:25 UTC by rajvi-patel-22

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
Workflow

User goes to concept list page

User selects a concept that has not be resolved

If there is a viaf url, Vogon will search Conceptpower for that viaf url and show the result. If there is exactly one result, user should be able to say “approve”, if there are more, user should select one

User should also have the chance to do a conceptpower search for a search term and select one of the results.

If there is no viaf url, user should get a  search  field to search conceptpower and then be able to select one of the results or do a new search

For all of these options, there should also be a button to create a new concept in conceptpower.

Once a concept has been selected and approved, Vogon concept is RESOLVED

We will likely only have “Pending” and “resolved” as concept states.

... Put ticket description here and add link to ticket ...
https://diging.atlassian.net/browse/VOGRE-32

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?
Below bug is fixed along with this PR:
- Fix this.label for new concept nam/label

2024-12-19 14:35 UTC, jdamerow requested changes

2024-12-19 14:35 UTC, jdamerow commented on concepts/lifecycle.py
> +                raise RuntimeError(response.status_code, response.text)
this should happen in a conceptpower class not directly here.

2024-12-19 14:35 UTC, jdamerow commented on concepts/lifecycle.py
> +
remove empty line

2024-12-19 14:35 UTC, jdamerow commented on concepts/lifecycle.py
> +                        concepts.append(concept)
same as above, should not happen in this class

2024-12-19 14:35 UTC, jdamerow commented on concepts/lifecycle.py
> +                        concepts.append(concept)
same

2024-12-19 14:35 UTC, jdamerow commented on concepts/lifecycle.py
> +                raise ValueError(f"Error fetching concept data: {response.status_code}")
same, there should be a conceptpower class that does all the communication with conceptpower (isn't there one already?)

2025-01-08 14:42 UTC, jdamerow requested changes

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +                "endpoint", "http://chps.asu.edu/conceptpower/rest/")
these should not be hard-coded; if a default is needed it should come from environment variables/settings.

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +               "namespace", "{http://www.digitalhps.org/}")
same here

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +        if response.status_code == 200:
if not, we definitely want to log what else is returned and an error message if there is one.

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +        if response.status_code == 200:
same here

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +        if response.status_code == 200:
also, you want to use a constant (`requests` probably has one) and not a magic number (even though it's an obvious one if you have done web application development before).

2025-01-08 14:42 UTC, jdamerow commented on concepts/conceptpower.py
> +        Parse a concept and return a dictionary with the required fields.
needs parameter description (what does this method accept to get in `concept_entry`? maybe even put in example json (think about what would someone need to know to use this method if they don't see the code)).

2025-01-24 16:25 UTC, jdamerow requested changes

2025-01-24 16:25 UTC, jdamerow commented on concepts/conceptpower.py
> +    # Default behavior is to leave these to the constructor.
what does this mean?

2025-01-24 16:25 UTC, jdamerow commented on concepts/conceptpower.py
> +        # Give first priority to the class definition, if endpoint or namespace are defined (and not None).
what does that mean?

2025-01-24 16:25 UTC, jdamerow commented on vogon/settings.py
> +CONCEPTPOWER_NAMESPACE = os.environ.get('CONCEPTPOWER_NAMESPACE', '{http://www.digitalhps.org/}')
why is the namespace in curly brackets?

2025-01-24 16:25 UTC, jdamerow commented on vogon/settings.py
> +CONCEPTPOWER_ENDPOINT = os.environ.get('CONCEPTPOWER_ENDPOINT', 'http://chps.asu.edu/conceptpower/rest/')
and let's not put that url here. even though it is in the github commit history now, we want to keep bot traffic to our servers as low as possible

2025-01-24 16:25 UTC, jdamerow commented on vogon/settings.py
> +CONCEPTPOWER_NAMESPACE = os.environ.get('CONCEPTPOWER_NAMESPACE', '{http://www.digitalhps.org/}')
this one is fine, it's just a static github page

2025-01-28 15:17 UTC, rajvi-patel-22 commented on vogon/settings.py
> +CONCEPTPOWER_NAMESPACE = os.environ.get('CONCEPTPOWER_NAMESPACE', '{http://www.digitalhps.org/}')
> why is the namespace in curly brackets?

Based on the old code and the places where it has been used, it seems to be enclosed in curly braces..
I have referred `conceptpower-api` repo ([here](https://github.com/diging/Conceptpower-API/blob/master/conceptpower/classes.py#L36))

Places where it's being used:  [here](https://github.com/diging/vogon-resuscitate/blob/develop/concepts/authorities.py#L131)

2025-01-28 15:52 UTC, jdamerow commented on vogon/settings.py
> +CONCEPTPOWER_NAMESPACE = os.environ.get('CONCEPTPOWER_NAMESPACE', '{http://www.digitalhps.org/}')
That doesn't seem to make sense. The `get_namespace` puts curly brackets around the namespace when returning, is that needed anywhere? why not drop them altogether (in the method and the environment variable)? It's not logical at all why I would add curly brackets around a namespace when configuring the application.

2025-02-06 15:10 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-06 15:40 UTC, jdamerow commented
this seems to break Vogon:
```
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  |   File "/vogon/concepts/admin.py", line 10, in <module>
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  |     from . import authorities
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  |   File "/vogon/concepts/authorities.py", line 6, in <module>
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  |     from conceptpower import Conceptpower
Feb 06 15:14:56 ubuntu20 docker[259738]: web-1  | ModuleNotFoundError: No module named 'conceptpower'
```

2025-02-20 16:24 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-20 16:25 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-20 16:40 UTC, jdamerow commented
When I try to resolve a concept, it asks me to login as admin. That shouldn't happen if I'm a Vogon admin.
Also, in the filter dropdown for concepts, do all these statuses still exist (e.g. approved)?

2025-03-07 15:53 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-07 16:08 UTC, jdamerow commented
I'm getting a 401 when I try to resolve a concept. My user is a Vogon Admin.

2025-03-13 18:03 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-13 18:09 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-13 18:13 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-21 14:50 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-21 15:27 UTC, jdamerow reviewed
After a concept has been merge, the uri that is shown should be the Concetppower one, but I'm going to merge this and create a new ticket for this.

2025-03-21 15:27 UTC, merged